name: praise_resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v4
    - name: spell check
      uses: rojopolis/spellcheck-github-actions@0.34.0
      with:                                        
        task_name: Markdown
        output_file: spellcheck-output.txt
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v4
    - name: build resume
      uses: docker://ghcr.io/qjoly/xelatex:latest
      with:
        args: |
          praise_tompane_resume.tex
    - name: setup release folder
      run: mkdir -p ./release && cp praise_tompane_resume.pdf ./release
    - name: publish document
      uses: actions/upload-artifact@v4
      with:
        path: |
          praise_tompane_resume.pdf